### PR TITLE
Addition of ros-time and automatically load packages in ros-publish

### PR DESCRIPTION
**Pull request by jorritgoos**
Changes:

- ros-time: added function which outputs ROS time stamp
- ros-subscribe: commented print statement
- ros-publish: commented print statement, added function to automatically get all compiled ROS messages, added checkbox to inject ROS time stamp in msg.

### CODE REVIEW

**Comment by jorritgoos** [comment]
@namgk Hi, could you evaluate this request and merge it in the repo which is linked to npm. This would help me in installing this package on other machines. Thanks in advance!

**Comment by namgk** [comment]
Hi there,

Thanks for the PR.

If the inclusion of rosnodejs is just for using its Time, see if you can include their code directly without having to add a dependency?

Basically just add the Time class and the utils libraries here:

https://github.com/RethinkRobotics-opensource/rosnodejs/blob/kinetic-devel/src/lib/Time.js

and here

https://github.com/RethinkRobotics-opensource/rosnodejs/blob/kinetic-devel/src/utils/time_utils.js

**Comment by jorritgoos** [comment]
@namgk Hi, thanks for the respose. I included the code from rosnodejs directly.

**Comment by namgk** [comment]
How do you serve this? I don't see any server code that serving this request.

    $.getJSON('packages', function(list) {

**Comment by jorritgoos** [comment]
I am not quite sure if I understand your question, but next to node-red, I launch a rosbridge_websocket via: `roslaunch rosbridge_server rosbridge_websocket.launch`.

**Comment by namgk** [comment]
Can I launch the bridge at a different computer or at a port that is not
80, I don’t see how this can be possible.

**Comment by jorritgoos** [comment]
In one terminal I start the node-red node and on a second one I launch the rosbridge_server according to the command below. That command creates websocket server at: ws://0.0.0.0:9090

But also without that server I can select all the compiled msgs in my workspace. 

I used [snappy-ros](https://github.com/SnappyRobotics/snappy-ros) as a reference for changing the files.

**Comment by namgk** [comment]
What I found when I try your code is 404 not found for /packages. This is
from the dev console of Chrome and happens when I double click on the node
to configure it.

Can you try to just run node red without any ros terminals? I think you
might need better error handling in such cases.

**Comment by jorritgoos** [comment]
When I run only node-red with the command `node-red`, I can configure the nodes publish, subscribe and time properly without an error. The only error I get is because it cannot connect to the ros-server. The node time also works.

I tested the code on a windows laptop without ROS and then it gives this error: typeerror util.debug is not a function. But this one is also present when I launch node-red with your code. 

Do you have tips for me on how to test the code and create better error handling

**Comment by namgk** [comment]
Hi, I think it's best to give you a maintainer role, so that you can answer any future issue on this package.

Please check the invitation.

Also let me know your npm user so that I can allow you to publish the package too.

**Comment by jorritgoos** [comment]
I just created an NPM account: 
Name: goosj
Email: jorritgoos@gmail.com

So whats next. Were you able to use my changes without errors or not yet?

**Comment by namgk** [comment]
I don't have a ros installation to try right now. I can only look at the
code and try the node alone.

It's better for you to be the owner of the code so you can test and fix any
upcoming bugs.

Cheers

**Comment by jorritgoos** [comment]
Can I merge the pull request then? 

And what do I need to do to link this update to NPM such that it can be updated in node-red? 

Sorry for all the questions.

**Comment by namgk** [comment]
no worry, you can do whatever you want now with the repo as you're the maintainer now. 

I've given you write access to the npm registry, so you can just do npm login, and then npm publish within the package to publish it.

**Pull request merged**
